#!/usr/bin/fish -i

function ask
	read -P "$argv[1] [Y/N] " ask_continue
	if contains $ask_continue "Y" "y"
		return 0
	else
		return 1
	end
end

function exit_if_fail
	eval $argv
	if test $status -ne 0
		echo "Command \"$argv\" failed, exiting"
		exit 1
	end
end

function single_plural
	if test $argv[1] -eq 1
		echo $argv[2]
	else
		echo $argv[3]
	end
end

function path_check
	set missingfile 0
	for file in $argv
		if not test -e $file
			set missingfile (math $missingfile + 1)
			echo "Couldn't find file $file."
		end
	end

	if test $missingfile -gt 0
		set f (single_plural $missingfile "file" "files")
		echo "$missingfile $f missing, is \$PWD ($PWD) correct? Exiting."
		exit 1
	end
end

source configs/fish/config.fish

if ask "This will overwrite existing config files, continue?"
	path_check "configs"
	ln -sf $PWD/configs/* ~/.config
end

if ask "Install your packages?"
	path_check "packages.list"
	exit_if_fail update

	set install_list
	for x in (cat packages.list)
		if     test -n $x
		   and not has_installed $x
			set install_list $install_list $x
		end
	end

	if test -n "$install_list"
		sudo pacman -S $install_list
	else
		echo "All packages were already installed!"
	end
end

if ask "Overwrite xinitrc?"
	path_check "synaptics.sh"
	echo "# This file was automatically generated by dotfiles/install.fish" > ~/.xinitrc
	echo "$PWD/synaptics.sh" >> ~/.xinitrc
	echo "exec i3"           >> ~/.xinitrc
end
